#!/usr/bin/env ruby

require 'rubygems'
require 'servitude'

# The simple server is as actually not a true server at all as it does nothing except for start and run (serving no
# requests).  
#
# Use CTRL-c (INT signal) to stop the server. Additionally send the process an INT or TERM signal using the kill comand 
# or your # OS's # process monitoring application.  All 3 strategies result in a graceful shutdown as displayed by the 
# 'Shutting down ...' which occurs due to the finalize block.
#
# Usage:
#   bundle exec examples/1_simple_server
#
module SimpleServer

  include Servitude::Base

  APP_FOLDER = 'simple-server'
  VERSION    = '1.0.0'

  PROJECT_ROOT = File.expand_path( '../..', __FILE__ )
  
  boot app_id: 'simple-server',
       app_name: 'Simple Server',
       attribution: "v#{VERSION} \u00A9#{Time.now.year} LFE",
       author: 'LFE',
       use_config: false,
       default_config_path: nil

  class Server

    include Servitude::Server

    finalize do
      info 'Shutting down ...'
    end

    def run
      info "Running ..."
    end

  end
end

SimpleServer::Server.new.start
